OrdererOrgs:
  - Name: Orderer
    Domain: supply.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org1
  - Domain: org1.supply.com
    EnableNodeOUS: true
    Template:
      Count: 2
    Users:
      Count: 5

  - Name: Org2
  - Domain: org2.supply.com
    EnableNodeOUS: true
    Template:
      Count: 2
    Users:
      Count: 5